---
- name: Create and configure a Linux EC2 instance
  hosts: localhost
  gather_facts: false
  vars:
    ec2_name_tag: "{{ ec2_name_tag | default('') }}"
    aws_region: "{{ aws_region | default('') }}"
    vpc_id: "{{ vpc_id | default('') }}"
    subnet_id: "{{ subnet_id | default('') }}"
    ami_id: "{{ ami_id | default('') }}"
    instance_type: "{{ instance_type | default('t3.micro') }}"
    iam_instance_profile_arn: "{{ iam_instance_profile_arn | default('') }}"
    root_volume_size: "{{ root_volume_size | default('30') }}"
    root_volume_type: "{{ root_volume_type | default('gp2') }}"
    root_volume_encrypted: "{{ root_volume_encrypted | default(false) }}"
    root_volume_delete_on_termination: "{{ root_volume_delete_on_termination | default(true) }}"
    key_name: "{{ ec2_name_tag }}-linux-ec2-key"
    vault_secret_path: "linux/{{ key_name }}"
    security_group_name: "linux-ec2-sg"
    associate_eip: true

  tasks:
    - name: Validate required parameters
      ansible.builtin.assert:
        that:
          - aws_region != ''
          - ami_id != ''
          - ec2_name_tag != ''
        fail_msg: "All required parameters (region, ami-id, ec2 name tag) must be set."

    - name: Lookup default VPC if vpc_id not provided
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          isDefault: true
      register: default_vpc_info
      when: vpc_id == ''

    - name: Set vpc_id to default if not provided
      ansible.builtin.set_fact:
        vpc_id: "{{ default_vpc_info.vpcs[0].vpc_id }}"
      when: vpc_id == '' and default_vpc_info.vpcs | length > 0

    - name: Lookup default subnet if subnet_id not provided
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ aws_region }}"
        filters:
          defaultForAz: true
          vpc-id: "{{ vpc_id }}"
      register: default_subnet_info
      when: subnet_id == ''

    - name: Set subnet_id to default if not provided
      ansible.builtin.set_fact:
        subnet_id: "{{ default_subnet_info.subnets[0].id }}"
      when: subnet_id == '' and default_subnet_info.subnets | length > 0

    - name: Create temporary file for Vault CA cert
      ansible.builtin.tempfile:
        state: file
        suffix: .crt
      register: vault_ca_cert_file

    - name: Write Vault CA cert to file
      ansible.builtin.copy:
        content: "{{ lookup('env', 'VAULT_CA_CERT_PEM') }}"
        dest: "{{ vault_ca_cert_file.path }}"
        mode: '0644'

    - name: Check Vault connection
      community.hashi_vault.vault_login:
        url: "{{ lookup('env', 'VAULT_ADDR') }}"
        auth_method: approle
        role_id: "{{ lookup('env', 'VAULT_ROLE_ID') }}"
        secret_id: "{{ lookup('env', 'VAULT_SECRET_ID') }}"
        ca_cert: "{{ vault_ca_cert_file.path }}"
        validate_certs: true
      register: vault_login_result
      failed_when: vault_login_result.failed or (vault_login_result.status is defined and vault_login_result.status != 200)

    - name: Create security group
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: "Security group for Linux EC2 instance"
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
      register: sg_result

    - name: Create EC2 key pair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        state: present
      register: keypair_result

    - name: Launch and configure EC2 instance (with cleanup on failure)
      block:
        - name: Launch EC2 instance
          amazon.aws.ec2_instance:
            name: "{{ ec2_name_tag }}"
            key_name: "{{ key_name }}"
            instance_type: "{{ instance_type }}"
            image_id: "{{ ami_id }}"
            region: "{{ aws_region }}"
            subnet_id: "{{ subnet_id }}"
            security_group: "{{ sg_result.group_id }}"
            iam_instance_profile:
              arn: "{{ iam_instance_profile_arn }}"
            wait: true
            wait_timeout: 500
            count: 1
            volumes:
              - device_name: /dev/sda1
                ebs:
                  volume_type: "{{ root_volume_type }}"
                  volume_size: "{{ root_volume_size | int }}"
                  delete_on_termination: "{{ root_volume_delete_on_termination | bool }}"
                  encrypted: "{{ root_volume_encrypted | bool }}"
            tags:
              Name: "{{ ec2_name_tag }}"
          register: ec2_result

        - name: Associate Elastic IP (optional)
          when: associate_eip | bool
          amazon.aws.ec2_eip:
            region: "{{ aws_region }}"
            state: present
            device_id: "{{ ec2_result.instances[0].instance_id }}"
          register: eip_result

        - name: Store private key in Vault
          ansible.builtin.include_role:
            name: manage_secret
          vars:
            manage_secret_action: write
            manage_secret_path: "{{ vault_secret_path }}/{{ ec2_result.instances[0].instance_id }}"
            manage_secret_payload:
              private_key: "{{ keypair_result.key.private_key }}"

        - name: Output instance info
          ansible.builtin.debug:
            msg:
              - "Instance info: {{ ec2_result.instances }}"
              - "Elastic IP: {{ (associate_eip | bool) | ternary(eip_result.eip.public_ip, 'Not associated') }}"
      rescue:
        - name: Delete EC2 key pair if created
          amazon.aws.ec2_key:
            name: "{{ key_name }}"
            region: "{{ aws_region }}"
            state: absent
          ignore_errors: true

        - name: Delete EC2 instance if created
          when: ec2_result is defined and ec2_result.instances is defined and ec2_result.instances | length > 0
          amazon.aws.ec2_instance:
            instance_ids: "{{ ec2_result.instances[0].instance_id }}"
            region: "{{ aws_region }}"
            state: absent
            wait: true
          ignore_errors: true

        - name: Delete security group if created
          amazon.aws.ec2_group:
            name: "{{ security_group_name }}"
            region: "{{ aws_region }}"
            vpc_id: "{{ vpc_id }}"
            state: absent
          ignore_errors: true

        - name: Output cleanup info
          ansible.builtin.debug:
            msg: "Cleanup attempted for all created resources due to failure."
