---
- name: Create and configure a Linux EC2 instance
  hosts: localhost
  gather_facts: false
  vars:
    ec2_name_tag: "{{ ec2_name_tag | default('') }}"
    aws_region: "{{ aws_region | default('') }}"
    vpc_id: "{{ vpc_id | default('') }}"
    ami_id: "{{ ami_id | default('') }}"
    iam_instance_profile_arn: "{{ iam_instance_profile_arn | default('') }}"
    instance_type: "{{ instance_type | default('t3.micro') }}"
    key_name: "{{ ec2_name_tag }}-linux-ec2-key"
    vault_secret_path: "linux/{{ key_name }}"
    security_group_name: "linux-ec2-sg"
    associate_eip: "{{ associate_eip | default(false) }}"
    root_volume_size: "{{ root_volume_size | default(20) }}"  # Size in GB

  tasks:
    - name: Validate required parameters
      ansible.builtin.assert:
        that:
          - aws_region != ''
          - vpc_id != ''
          - ami_id != ''
          - iam_instance_profile_arn != ''
          - ec2_name_tag != ''
        fail_msg: "All required parameters (region, vpc-id, ami-id, iam arn, ec2 name tag) must be set."

    - name: Create security group
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: "Security group for Linux EC2 instance"
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
      register: sg_result

    - name: Create EC2 key pair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        state: present
      register: keypair_result

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ ec2_name_tag }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ aws_region }}"
        vpc_subnet_id: "{{ vpc_id }}"
        security_group: "{{ sg_result.group_id }}"
        iam_instance_profile:
          arn: "{{ iam_instance_profile_arn }}"
        wait: true
        count: 1
        tags:
          Name: "{{ ec2_name_tag }}"
        volumes:
          - device_name: /dev/xvda
            volume_size: "{{ root_volume_size }}"
            volume_type: gp3
            delete_on_termination: true
            encrypted: true
      register: ec2_result

    - name: Associate Elastic IP (optional)
      when: associate_eip | bool
      amazon.aws.ec2_eip:
        region: "{{ aws_region }}"
        state: present
        device_id: "{{ ec2_result.instances[0].instance_id }}"
      register: eip_result

    - name: Store private key in Vault
      ansible.builtin.include_role:
        name: manage_secret
      vars:
        manage_secret_action: write
        manage_secret_path: "{{ vault_secret_path }}//{{ ec2_result.instances[0].instance_id }}"
        manage_secret_payload:
          private_key: "{{ keypair_result.key.private_key }}"

    - name: Output instance info
      ansible.builtin.debug:
        msg:
          - "Instance info: {{ ec2_result.instances }}"
          - "Elastic IP: {{ (associate_eip | bool) | ternary(eip_result.eip.public_ip, 'Not associated') }}"
